### ISSUE TITLE
[Bug] running example code 

### ISSUE THREAD

**Issue by jonnieb007** [mitre-attack/mitreattack-python#107]
## Expected Behavior
get mitre groups 

## Actual Behavior
Errors 
ModuleNotFoundError: No module named 'drawSvg'

## Steps to Reproduce the Problem

  1. run the example [mitreattack-python](https://github.com/mitre-attack/mitreattack-python)/[examples](https://github.com/mitre-attack/mitreattack-python/tree/master/examples)/get_all_groups.py
  2.
  3.

## Possible Solution
Maybe linked on #106

**Comment by fmtakaki** [comment]
I could replicate the same issue and, for the first instance, it is happening because the module name installed automatically is draw**s**vg and not draw**S**vg (with capital S) . The changes that I made as workaround were:
1. replace the `import drawSvg` to `import drawsvg`
file: mitreattack\navlayers\exporters\svg_templates.py @ line 7
2. just like the previous but adding the statement `as` to avoid other changes along the code, from `import drawSvg` to `import drawsvg as drawSvg`
file: mitreattack\navlayers\exporters\svg_objects.py @ line 3

**Comment by jondricek** [comment]
This is definitely related to #106, and I just pushed up a fix to it to PyPI (mitreattack-python v2.0.5) that includes our official fix from the #108 PR.

As much as I would like to update our code to go from drawSvg 1.9.0 to drawsvg 2.x (they changed their name in the update), the quick fix mentioned by @fmtakaki will allow imports, but break the actual functionality of generating SVG files from ATT&CK Navigator layer files. So I'll be opening another (low-priority) issue to upgrade our SVG generation to use the latest version of the drawsvg library
