### ISSUE TITLE
Handle version 4.2 of the att&ck navigator

### ISSUE THREAD

**Issue by bartMarinissen** [mitre-attack/mitreattack-python#7]
I tried to load a layer json file made recently from the att&ck navigator as available online.

This yielded warnings about using a file with version 4.2 whilst the tool is only able to handle files up to version 4.1.

I believe version 4.2 of the navigator is older than the latest release of this tool. Hence I would have expected this tool to handle the latest version.

A plausible alternative for me would be to have access to an older version of the navigator, presuming the older version still contains the newest Mitre Att&ck matrix.

**Comment by ArtificialErmine** [comment]
The 4.2 Layer (which is what the live navigator produces) is almost completely compatible with this tool, and should be useable without incident despite the warnings, as the 4.2 Layer is a 4.1 Layer from the viewpoint of the current iteration of `mitreattack-python`. As for why it still prints the error - there are a few new fields that were introduced during the upgrade from 4.1 to 4.2 that aren't supported here, but these are basically just text fields for the moment, as they are intended to integrate with additional functionality that is still being developed on our end, both here and in other ATT&CK resources. Once that development has been completed, the library will be updated accordingly to remove the warning, but in the mean time, we've left it in as a notification to users that the future functionality alluded to in 4.2 has not yet been implemented. 

Feel free to keep using the 4.2 Layers produced by the online tool in the meantime though, as they are otherwise completely compatible.

**Comment by ArtificialErmine** [comment]
@bartMarinissen Thanks for reporting this! The problem should have been resolved with the recent [v1.1 release](https://github.com/mitre-attack/mitreattack-python/releases/tag/v1.1). If this is not the case, please let us know.
