### ISSUE TITLE
[Bug] Unable to install from Pip

### ISSUE THREAD

**Issue by IgorGanapolsky** [mitre-attack/mitreattack-python#77]
## Expected Behavior
Should be able to install this module by running `pip install mitreattack-python`

## Actual Behavior
It doesn't get installed.  When I run `from mitreattack.navlayers import Layer`, there is an error:
> ModuleNotFoundError: No module named 'mitreattack'

## Possible Solution
Make installer valid

**Comment by Thomas-McKanna** [comment]
On a macOS system with a fresh install of `mitreattack-python==1.5.7` I was able to run `from mitreattack.navlayers import Layer` without error.

**Comment by IgorGanapolsky** [comment]
I am on Python 3.11.  But it seems mitreattack expects Python 3.8
<img width="1266" alt="Screen Shot 2022-06-08 at 12 59 25 PM" src="https://user-images.githubusercontent.com/201209/172674462-b1bbb920-33d3-4c7c-8320-c61f84d4e866.png">
?

**Comment by jondricek** [comment]
Right now I'm targeting Python 3.8 for the library as you mentioned above. Locally I use Python 3.9 as well, so haven't caught up to 3.11 which is still in beta until this October (PEP 664: https://peps.python.org/pep-0664/)

Since this appears to be working on 3.8/3.9, I'll close this for now, but feel free to re-open a new issue for 3.11 once it comes out of beta if it still is failing.
